# Generated by Django 6.0 on 2026-01-01 12:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About St Joseph Mission School', max_length=200)),
                ('history', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('values', models.TextField(blank=True, help_text='List core values separated by commas')),
                ('achievements', models.TextField(blank=True, help_text='Notable achievements and awards')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facility_images/')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='about_app.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('school_commitee', 'School Commitee'), ('teacher', 'Teacher'), ('headmistress', 'Headmistress'), ('asst_headmistress', 'Asst. Headmistress'), ('dean_of_discipline', 'Dean of Discipline'), ('academic_dean', 'Academic Dean'), ('environment_head', 'Environment Head'), ('sports_and_games_head', 'Sports & Games Head'), ('board', 'Board Member')], max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about_app.aboutpage')),
            ],
            options={
                'ordering': ['order', 'position', 'name'],
            },
        ),
    ]
